name: Notify Subscribers of Updates

on:
  push:
    branches:
      - prerelease_changes
      - main
    paths:
      - 'src/events/**/*.md'
      - 'src/community_updates/**/*.md'

jobs:
  notify_onesignal:
    runs-on: ubuntu-latest
    steps:
      - name: Send OneSignal Push Notification
        run: |
          curl --request POST \
            --url https://onesignal.com/api/v1/notifications \
            --header "Authorization: Basic ${{ secrets.ONESIGNAL_REST_API_KEY }}" \
            --header "Content-Type: application/json" \
            --data '{
              "app_id": "${{ secrets.ONESIGNAL_APP_ID }}",
              "included_segments": ["Subscribed Users"],
              "contents": {"en": "A new community update or event has been posted on Maharashtra Mandal Krakow! Tap to view."},
              "headings": {"en": "New Update from MMKrakow!"}
            }'
